<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="tram"
    viewBox="0 0 100 50"
    width="250"
    height="150">
    <linearGradient
      id="field"
      x1="0"
      x2="0"
      y1="0"
      y2="1"
    >
      <stop
        stop-color="green"
        stop-opacity="0.9"
        offset="0%"/>
      <stop
        stop-color="#30a030"
        stop-opacity="0.5"
        offset="20%"/>
      <stop
        stop-color="#10e010"
        stop-opacity="0.8"
        offset="40%"/>
      <stop
        stop-color="#272"
        stop-opacity="0.8"
        offset="60%"/>
      <stop
        stop-color="#888"
        stop-opacity="0.6"
        offset="80%"/>
      <stop
        stop-color="#aaa"
        stop-opacity="0.7"
        offset="100%"/>
    </linearGradient>
    <linearGradient
      id="air"
      x1="0"
      x2="0"
      y1="0"
      y2="1"
    >
      <stop
        stop-color="blue"
        stop-opacity="0.9"
        offset="0%"/>
      <stop
        stop-color="blue"
        stop-opacity="0.7"
        offset="20%"/>
      <stop
        stop-color="blue"
        stop-opacity="0.6"
        offset="40%"/>
      <stop
        stop-color="#0559a9"
        stop-opacity="0.7"
        offset="80%"/>
      <stop
        stop-color="#4599e9"
        stop-opacity="0.9"
        offset="100%"/>
    </linearGradient>
    <rect
      x="-10.95"
      y="0"
      width="98.85"
      height="35"
      fill="url(#air)"
      stroke="blue"
      stroke-width="0.36"
    />
    <rect
      x="-11"
      y="35"
      width="98.85"
      height="10"
      fill="url(#field)"
      stroke="green"
      stroke-width="0.36"
    />
    <rect
      x="69"
      y="0"
      height="50"
      width="2"
      fill="#aaa"
    />
    <rect
      x="35"
      y="0"
      height="50"
      width="2"
      fill="#aaa"
    />
    <line
      x1="35"
      y1="24"
      x2="36"
      y2="19"
      stroke="#414141"
      stroke-width="0.95"
    />
    <rect
      x="38"
      y="10"
      width="3"
      height="5"
      fill="#deae96"
      stroke="#efefef"
      stroke-width="0.36"
      style="transform: rotateZ(9deg)"
    />
    <line
      x1="0"
      y1="8"
      x2="87"
      y2="8"
      stroke="black"
      stroke-width="0.45"
    />
    <line
      x1="0"
      y1="10.9"
      x2="87"
      y2="10.9"
      stroke="black"
      stroke-width="0.45"
    />
    <line
      x1="27"
      y1="6"
      x2="27"
      y2="10.9"
      stroke="black"
      stroke-width="0.85"
    />
    <line
      x1="62"
      y1="6"
      x2="62"
      y2="10.9"
      stroke="black"
      stroke-width="0.85"
    />
    <line
      x1="35"
      y1="2"
      x2="21"
      y2="10"
      stroke="#414141"
      stroke-width="0.95"
    />
    <line
      x1="69"
      y1="2"
      x2="55"
      y2="10"
      stroke="#414141"
      stroke-width="0.95"
    />
  </svg>
</template>
