<template>
  <g>
    <g
      v-if="color === 'red'"
      id="ktm5red">
      <linearGradient
        id="doorcolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#2294e0"
          stop-opacity="0.5"
          offset="0%"/>
        <stop
          stop-color="#5de4e0"
          stop-opacity="0.3"
          offset="20%"/>
        <stop
          stop-color="blue"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="#ed5450"
          stop-opacity="1"
          offset="45%"/>
        <stop
          stop-color="#ed1410"
          stop-opacity="1"
          offset="100%"/>
      </linearGradient>
      <linearGradient
        id="bodycolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#ed2420"
          stop-opacity="0.6"
          offset="0%"/>
        <stop
          stop-color="red"
          stop-opacity="0.8"
          offset="20%"/>
        <stop
          stop-color="#ed2420"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="red"
          stop-opacity="0.8"
          offset="60%"/>
        <stop
          stop-color="#ed2420"
          stop-opacity="0.6"
          offset="80%"/>
        <stop
          stop-color="red"
          stop-opacity="0.8"
          offset="100%"/>
      </linearGradient>
    </g>
    <g
      v-if="color === 'yellow'"
      id="ktm5yellow">
      <linearGradient
        id="doorcolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#2294e0"
          stop-opacity="0.5"
          offset="0%"/>
        <stop
          stop-color="#2de2c0"
          stop-opacity="0.3"
          offset="20%"/>
        <stop
          stop-color="blue"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="#bdc450"
          stop-opacity="1"
          offset="45%"/>
        <stop
          stop-color="#7d7220"
          stop-opacity="1"
          offset="100%"/>
      </linearGradient>
      <linearGradient
        id="bodycolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#7d7420"
          stop-opacity="0.6"
          offset="0%"/>
        <stop
          stop-color="#ada220"
          stop-opacity="0.8"
          offset="20%"/>
        <stop
          stop-color="#7d7420"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="#ada220"
          stop-opacity="0.8"
          offset="60%"/>
        <stop
          stop-color="#7d7420"
          stop-opacity="0.6"
          offset="80%"/>
        <stop
          stop-color="#ada220"
          stop-opacity="0.8"
          offset="100%"/>
      </linearGradient>
    </g>
    <g
      v-if="color === 'blue'"
      id="ktm5blue">
      <linearGradient
        id="doorcolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#2294e0"
          stop-opacity="0.5"
          offset="0%"/>
        <stop
          stop-color="#5de4e0"
          stop-opacity="0.3"
          offset="20%"/>
        <stop
          stop-color="blue"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="#5d54c0"
          stop-opacity="1"
          offset="45%"/>
        <stop
          stop-color="#3d34a0"
          stop-opacity="1"
          offset="100%"/>
      </linearGradient>
      <linearGradient
        id="bodycolor"
        x1="0"
        x2="0"
        y1="0"
        y2="1"
      >
        <stop
          stop-color="#2d24c0"
          stop-opacity="0.6"
          offset="0%"/>
        <stop
          stop-color="#2227a0"
          stop-opacity="0.8"
          offset="20%"/>
        <stop
          stop-color="#3d34a0"
          stop-opacity="0.6"
          offset="40%"/>
        <stop
          stop-color="#2227a0"
          stop-opacity="0.8"
          offset="60%"/>
        <stop
          stop-color="#3d34a0"
          stop-opacity="0.6"
          offset="80%"/>
        <stop
          stop-color="#2227a0"
          stop-opacity="0.8"
          offset="100%"/>
      </linearGradient>
    </g>
  </g>
</template>
<script>
export default {
  props: {
    color: {
      type: String,
      default: 'red'
    }
  }
}
</script>
